### ISSUE TITLE
How to debug Flow?

### ISSUE THREAD

**Issue by villesau** [hackwaly/vscode-ocaml-debugger#5]
Flow has issue of debugging, and people has succeeded to debug it with certain configurations: https://github.com/facebook/flow/issues/4181

Anyhow, with `vscode-ocaml-debugger` I have not been able to start debug session with flow. Looks like nothing happens with following config, just endless blue loading bar appears and thats it:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "OCaml",
            "type": "ocaml-debugger",
            "request": "launch",
            "program": "${workspaceFolder}/bin/flow",
            "console": "internalConsole",
            "stopOnEntry": false,
            "arguments": ["check", "${workspaceFolder}/my-own-test/test.js", "--max-workers", "0"]
          }
    ]
}
```

Would be nice to see some logging if there is e.g something that goes wrong.

**Comment by hackwaly** [comment]
I've not enough time to address your issue. You can use ocaml-debugger to debug ocaml-debugger to debug flow to check out what happens.

First you need clone git@github.com:hackwaly/ocamlearlybird.git, Use vscode open the project folder. Then use this configuration to debug ocamlearlybird.

```
    {
      "name": "Debugger",
      "type": "ocaml-debugger",
      "request": "launch",
      "program": "${workspaceRoot}/_build/default/ocaml_debug_adapter/main.bc",
      "arguments": ["--server", "--port=4712"],
      "preLaunchTask": "build",
      "console": "internalConsole",
      "env": {
        "OCAMLRUNPARAM": "b"
      }
    },
```

Then use the debugged ocamlearlybird to debug flow:

```
        {
            "name": "OCaml",
            "type": "ocaml-debugger",
            "request": "launch",
            "program": "${workspaceFolder}/bin/flow",
            "console": "internalConsole",
            "stopOnEntry": false,
            "arguments": ["check", "${workspaceFolder}/my-own-test/test.js", "--max-workers", "0"],
            "debugServer": 4712
          }
```

**Comment by hackwaly** [comment]
@villesau This should be fixed as I removed the unnecessary `ocamlrun`.
Track progress https://github.com/ocaml/opam-repository/pull/13149

**Comment by villesau** [comment]
@hackwaly Nice, thanks! Works like a charm now!
